<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__3</name>
   <tag></tag>
   <elementGuidId>54072714-7cef-4cfb-a3c5-9ec387ea44d0</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-menu__label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>新增</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;wrapper&quot;]/span[@class=&quot;modals&quot;]/div[@class=&quot;fileUpload&quot;]/div[@class=&quot;fuModalContainer&quot;]/div[@class=&quot;modalBox modalBox--fm&quot;]/div[@class=&quot;content--aa&quot;]/div[@class=&quot;uploadContentBox&quot;]/ul[1]/li[@class=&quot;uploadBoxContainer&quot;]/div[@class=&quot;flex_1&quot;]/div[@class=&quot;tagsBoxContainer&quot;]/div[@class=&quot;dropAddMenu&quot;]/div[@class=&quot;dropdown-menu&quot;]/div[@class=&quot;dropdown-menu__label&quot;]</value>
   </webElementProperties>
</WebElementEntity>
