<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_</name>
   <tag></tag>
   <elementGuidId>078768ae-77b9-475f-b48e-e82b11413284</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select__list-item</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>參展</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>參展</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;wrapper&quot;]/span[@class=&quot;modals&quot;]/div[@class=&quot;fileUpload&quot;]/div[@class=&quot;fuModalContainer&quot;]/div[@class=&quot;modalBox modalBox--fm&quot;]/div[@class=&quot;content--aa&quot;]/div[@class=&quot;uploadContentBox&quot;]/ul[1]/li[@class=&quot;uploadBoxContainer&quot;]/div[@class=&quot;flex_1&quot;]/div[@class=&quot;tagsBoxContainer&quot;]/div[@class=&quot;tagBoxContainer&quot;]/div[@class=&quot;value--fm&quot;]/div[@class=&quot;select--comp&quot;]/div[@class=&quot;async-select&quot;]/div[1]/div[@class=&quot;select select--active&quot;]/div[@class=&quot;select__opts select__opts--show&quot;]/ul[@class=&quot;select__list&quot;]/li[@class=&quot;select__list-item&quot;]</value>
   </webElementProperties>
</WebElementEntity>
