<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__5</name>
   <tag></tag>
   <elementGuidId>1d6a829f-7bbf-48de-b167-0f34cdd99065</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>確認</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;wrapper&quot;]/span[@class=&quot;modals&quot;]/div[@class=&quot;fileUpload&quot;]/div[@class=&quot;fuModalContainer&quot;]/div[@class=&quot;modalBox modalBox--fm&quot;]/div[@class=&quot;footer&quot;]/span[@class=&quot;btn btnSumbit&quot;]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
