<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__2</name>
   <tag></tag>
   <elementGuidId>aab5982c-866a-4a49-9ba3-fb71e6baa773</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>報告類</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;wrapper&quot;]/span[@class=&quot;modals&quot;]/div[@class=&quot;fileUpload&quot;]/div[@class=&quot;fuSelectProject&quot;]/div[1]/div[@class=&quot;contentbox&quot;]/div[@class=&quot;contentbox--body&quot;]/div[@class=&quot;bodyBox&quot;]/div[@class=&quot;itemList wd1_1&quot;]/div[@class=&quot;body&quot;]/li[@class=&quot;productList&quot;]/div[1]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
