<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__1</name>
   <tag></tag>
   <elementGuidId>556386b7-9244-4a2f-ae41-ec26d319043b</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-menu__list-label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>檔案上傳</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;wrapper&quot;]/div[2]/span[@class=&quot;content doc-management&quot;]/div[@class=&quot;advance-search&quot;]/div[@class=&quot;advance-search__collapse&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;advance-search__add-doc-btn&quot;]/div[@class=&quot;dropdown-menu dropdown-menu--active&quot;]/div[@class=&quot;dropdown-menu__opts dropdown-menu__opts--show&quot;]/ul[@class=&quot;dropdown-menu__list&quot;]/li[@class=&quot;dropdown-menu__list-item&quot;]/span[@class=&quot;dropdown-menu__list-label&quot;]</value>
   </webElementProperties>
</WebElementEntity>
