<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_radio-icon</name>
   <tag></tag>
   <elementGuidId>1fbe7a0a-58e4-4991-b6b2-d3e34c295af6</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-icon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;wrapper&quot;]/span[@class=&quot;modals&quot;]/div[@class=&quot;fileUpload&quot;]/div[@class=&quot;fuSelectProject&quot;]/div[1]/div[@class=&quot;contentbox&quot;]/div[@class=&quot;contentbox--body&quot;]/div[@class=&quot;titleContent&quot;]/ol[@class=&quot;radio-list&quot;]/li[@class=&quot;radio&quot;]/span[@class=&quot;radio__span&quot;]/span[@class=&quot;radio-icon&quot;]</value>
   </webElementProperties>
</WebElementEntity>
