<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg</name>
   <tag></tag>
   <elementGuidId>2d840824-26b2-46ae-8205-8a1969804b1e</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>currentColor</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>preserveAspectRatio</name>
      <type>Main</type>
      <value>xMidYMid meet</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1em</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1em</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 40 40</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;wrapper&quot;]/div[2]/span[@class=&quot;content doc-management&quot;]/div[@class=&quot;doc-management__result&quot;]/div[@class=&quot;container&quot;]/main[@class=&quot;doc-management__result-main&quot;]/div[@class=&quot;search-docs&quot;]/div[@class=&quot;search-docs__body&quot;]/div[@class=&quot;search-docs__rows&quot;]/div[@class=&quot;cardList&quot;]/div[@class=&quot;cardList&quot;]/div[@class=&quot;cardList-cardBox&quot;]/div[@class=&quot;cardList-cardBox__cardTool&quot;]/div[@class=&quot;cardList-cardBox__cardTool-div&quot;]/div[@class=&quot;cardList-cardBox__cardTool-icon&quot;]/svg[1]</value>
   </webElementProperties>
</WebElementEntity>
